
MessagingChannel: 'BungeeCord'

list-ranks:
  default:
    priority: 6
  admin:
    priority: 0
    
utilities: 
  ports:
    survival: 25567
    skywars: 25568
    minigames: 25570
  servers:
    - 'survival'
    - 'skywars'
    - 'minigames'
    
queue:
  send-delay: 10  ## 20 = 1 segundo mi rey.
  servers:
    - 'Survival'
    - 'Skywars'
    - 'MiniGames'
    
NO_PERMISSION: "&cNo tienes permisos."
INVALID_NUMBER: "&cNumero Invalido."
NOT_IN_QUEUE: 
  - "&cNo te encuentras en ninguna Cola!"
QUEUE_LEFT: 
  - "&bNo estas en la cola de &3%server%&b."
INVALID_QUEUE: 
  - "&cCola no encontrada."
QUEUE_PAUSED: 
  - "&cLa cola de %server% ha sido pausada."
QUEUE_UNPAUSED: 
  - "&aLa cola de %server% ha sido resumiad."
LIMIT_SET: 
  - "&aSe ha impuesto un limite de %amount% en la cola %server%."
QUEUE_MESSAGE:
  - "&7&m------------------------------------"
  - "&bEstas en la posicion &3&l%position%&b/&3&l%total% &ben &3&l%server%&b."
  - "&bPara obtener una prioridad mas alta, compra paquete de permisos."
  - "&7&m------------------------------------"
QUEUE_SENT: 
  - "&aEnviandote a %server%."